/**
 * Compiles Testate into standalone executables with `bun build --compile`, one file per target,
 * with the built SPA and the migrations inside it.
 *
 *   bun scripts/binary/build-binaries.ts [--all | --target <key> ...] [--skip-web]
 *
 * The runtime reads the SPA and the migrations from a directory (`ops.basepath.ts`,
 * `lib/db/index.ts`), so a binary has to carry them and unpack them at boot. Bun embeds a file
 * for every `import ... with { type: "file" }` the entry reaches, so this script writes one such
 * import per file into `apps/api/src/embedded.ts` for the length of the compile and puts the
 * committed stub back afterwards; `ops.embedded.ts` does the unpacking. Defaults to the host
 * target. Output lands in `.bin-build/<os>_<arch>/testate`, which is ignored;
 * `scripts/binary/package.sh` turns that into the release archives and `checksums.txt`.
 */
import { readdirSync } from "node:fs";
import { join, relative } from "node:path";

const ROOT = new URL("../..", import.meta.url).pathname;
const STUB = join(ROOT, "apps/api/src/embedded.ts");
const WEB = join(ROOT, "apps/web/dist");
const MIGRATIONS = join(ROOT, "apps/api/src/db/migrations");
const OUT = join(ROOT, ".bin-build");

type Target = { key: string; bun: string; suffix: string };

// The key is the archive's name: Docker's architecture words (docs/decisions/2026-10-10-native-
// binaries.md, Q1). Linux x64 is Bun's baseline build, which runs on CPUs without AVX2 (Q2).
const TARGETS: readonly Target[] = [
  { key: "linux_amd64", bun: "bun-linux-x64-baseline", suffix: "" },
  { key: "linux_arm64", bun: "bun-linux-arm64", suffix: "" },
  { key: "darwin_arm64", bun: "bun-darwin-arm64", suffix: "" },
  { key: "darwin_amd64", bun: "bun-darwin-x64", suffix: "" },
  { key: "windows_amd64", bun: "bun-windows-x64", suffix: ".exe" },
];

function hostTarget(): Target {
  const os = process.platform === "win32" ? "windows" : process.platform;
  const key = `${os}_${process.arch === "x64" ? "amd64" : process.arch}`;
  const found = TARGETS.find((target) => target.key === key);
  if (found === undefined) throw new Error(`no binary target for this host: ${key}`);
  return found;
}

function chosen(args: readonly string[]): Target[] {
  if (args.includes("--all")) return [...TARGETS];
  const keys = args.filter((arg, index) => args[index - 1] === "--target");
  if (keys.length === 0) return [hostTarget()];
  return keys.map((key) => {
    const found = TARGETS.find((target) => target.key === key);
    if (found === undefined)
      throw new Error(`unknown target ${key}; one of ${TARGETS.map((t) => t.key).join(", ")}`);
    return found;
  });
}

/** Every file under `dir`, as paths relative to it, sorted so the generated module is stable. */
function filesUnder(dir: string): string[] {
  return readdirSync(dir, { recursive: true, withFileTypes: true })
    .filter((entry) => entry.isFile() && !entry.name.endsWith(".map"))
    .map((entry) => relative(dir, join(entry.parentPath, entry.name)))
    .sort();
}

/** The `embedded.ts` that carries every file: one import each, then the list the runtime reads. */
function embeddedSource(): string {
  const entries = [
    ...filesUnder(WEB).map((file) => ({ path: `web/${file}`, from: `../../web/dist/${file}` })),
    ...filesUnder(MIGRATIONS).map((file) => ({
      path: `migrations/${file}`,
      from: `./db/migrations/${file}`,
    })),
  ];
  const imports = entries.map(
    (entry, index) => `import f${index} from "${entry.from}" with { type: "file" };`
  );
  const list = entries.map((entry, index) => `  { path: "${entry.path}", file: f${index} },`);
  return [
    "// Generated by scripts/binary/build-binaries.ts for one compile. Not committed.",
    ...imports,
    "",
    "export type EmbeddedFile = { path: string; file: string };",
    "",
    "export const EMBEDDED: readonly EmbeddedFile[] = [",
    ...list,
    "];",
    "",
  ].join("\n");
}

async function run(command: string[], cwd = ROOT): Promise<void> {
  const proc = Bun.spawn(command, { cwd, stdout: "inherit", stderr: "inherit" });
  const code = await proc.exited;
  if (code !== 0) throw new Error(`${command.join(" ")} exited ${code}`);
}

async function compile(target: Target): Promise<string> {
  const outfile = join(OUT, target.key, `testate${target.suffix}`);
  await run([
    "bun",
    "build",
    "--compile",
    `--target=${target.bun}`,
    "--minify",
    "--sourcemap=none",
    "--external",
    "*.node",
    "apps/api/src/index.ts",
    "--outfile",
    outfile,
  ]);
  return outfile;
}

const args = process.argv.slice(2);
const targets = chosen(args);
if (!args.includes("--skip-web")) await run(["bun", "run", "build:web"]);
const stub = await Bun.file(STUB).text();
try {
  await Bun.write(STUB, embeddedSource());
  for (const target of targets) {
    const outfile = await compile(target);
    const size = Bun.file(outfile).size;
    console.log(`${relative(ROOT, outfile)}  ${(size / 1024 / 1024).toFixed(1)} MB`);
  }
} finally {
  // The stub goes back whatever happened above, or a source checkout would try to import a
  // dist that may not exist.
  await Bun.write(STUB, stub);
}
